using System;
using System.Collections.Generic;
using System.Linq;

namespace FoundryRulesAndUnits.Units.Specifications
{
    /// <summary>
    /// Base implementation providing universal conversion logic via base unit hub architecture
    /// </summary>
    public abstract class BaseUnitSystemSpecification : IUnitSystemSpecification
    {
        public abstract string SystemName { get; }
        public abstract Dictionary<UnitFamilyName, string> GetBaseUnits();
        public abstract Dictionary<string, UnitDefinition> GetUnitDefinitions();
        public abstract Dictionary<string, UnitConversion> GetBaseUnitConversions();
        public abstract Dictionary<string, string> GetUnitDisplayNames();
        
        public UnitFamilyName GetUnitFamily(string unitSymbol)
        {
            var unitDef = GetUnitDefinitions().Values.FirstOrDefault(u => u.Symbol == unitSymbol);
            return unitDef?.Family ?? UnitFamilyName.None;
        }
        
        /// <summary>
        /// Universal conversion method: any unit to any unit via base unit hub
        /// </summary>
        public double Convert(double value, string fromUnit, string toUnit)
        {
            if (fromUnit == toUnit) 
                return value;
                
            var fromFamily = GetUnitFamily(fromUnit);
            var toFamily = GetUnitFamily(toUnit);
            
            if (fromFamily != toFamily)
                throw new InvalidOperationException($"Cannot convert between different unit families: {fromFamily} -> {toFamily}");
                
            var baseUnit = GetBaseUnits()[fromFamily];
            
            // Direct conversion if one unit is already the base unit
            if (fromUnit == baseUnit)
                return ConvertFromBase(value, baseUnit, toUnit);
            if (toUnit == baseUnit)
                return ConvertToBase(value, fromUnit, baseUnit);
                
            // Two-step conversion: fromUnit -> baseUnit -> toUnit
            var valueInBase = ConvertToBase(value, fromUnit, baseUnit);
            return ConvertFromBase(valueInBase, baseUnit, toUnit);
        }
        
        /// <summary>
        /// Convert from any unit to its base unit using UnitDefinition's ToBaseUnit function
        /// </summary>
        private double ConvertToBase(double value, string fromUnit, string baseUnit)
        {
            // First try the smart UnitDefinition approach
            var unitDefinitions = GetUnitDefinitions();
            if (unitDefinitions.TryGetValue(fromUnit, out var unitDef) && unitDef.ToBaseUnit != null)
            {
                return unitDef.ToBaseUnit(value);
            }
            
            // Fallback to legacy hard-coded conversions
            var conversionKey = $"{fromUnit}|{baseUnit}";
            var conversions = GetBaseUnitConversions();
            
            if (conversions.TryGetValue(conversionKey, out var conversion))
                return conversion.Convert(value);
                
            throw new InvalidOperationException($"Missing conversion from {fromUnit} to base unit {baseUnit}");
        }
        
        /// <summary>
        /// Convert from base unit to any other unit using UnitDefinition's FromBaseUnit function
        /// </summary>
        private double ConvertFromBase(double value, string baseUnit, string toUnit)
        {
            // First try the smart UnitDefinition approach
            var unitDefinitions = GetUnitDefinitions();
            if (unitDefinitions.TryGetValue(toUnit, out var unitDef) && unitDef.FromBaseUnit != null)
            {
                return unitDef.FromBaseUnit(value);
            }
            
            // Fallback to legacy hard-coded conversions
            var conversionKey = $"{baseUnit}|{toUnit}";
            var conversions = GetBaseUnitConversions();
            
            if (conversions.TryGetValue(conversionKey, out var conversion))
                return conversion.Convert(value);
                
            throw new InvalidOperationException($"Missing conversion from base unit {baseUnit} to {toUnit}");
        }
        
        /// <summary>
        /// Gets combined conversions: auto-generated from UnitDefinition records + legacy hard-coded fallbacks
        /// This provides a migration path while we eliminate hard-coded matrices
        /// </summary>
        public Dictionary<string, UnitConversion> GetEffectiveConversions()
        {
            var effectiveConversions = new Dictionary<string, UnitConversion>();
            
            // Start with auto-generated conversions from UnitDefinition records
            var autoGenerated = GetAutoGeneratedBaseConversions();
            foreach (var kvp in autoGenerated)
            {
                effectiveConversions[kvp.Key] = kvp.Value;
            }
            
            // Add hard-coded conversions only for keys that don't exist yet
            var hardCoded = GetBaseUnitConversions();
            foreach (var kvp in hardCoded)
            {
                if (!effectiveConversions.ContainsKey(kvp.Key))
                {
                    effectiveConversions[kvp.Key] = kvp.Value;
                }
            }
            
            return effectiveConversions;
        }
        
        /// <summary>
        /// Auto-generates base unit conversions from UnitDefinition records
        /// Eliminates the need for hard-coded conversion matrices!
        /// </summary>
        public Dictionary<string, UnitConversion> GetAutoGeneratedBaseConversions()
        {
            var autoConversions = new Dictionary<string, UnitConversion>();
            var unitDefinitions = GetUnitDefinitions();
            var baseUnits = GetBaseUnits();
            
            foreach (var unitDef in unitDefinitions.Values)
            {
                var unitSymbol = unitDef.Symbol;
                var familyKey = unitDef.Family.ToString(); // "Length", "Mass", etc.
                
                // Check if we have a base unit for this family
                if (!baseUnits.TryGetValue(familyKey, out var baseUnit))
                    continue;
                
                // Skip if this IS the base unit
                if (unitSymbol == baseUnit)
                    continue;
                
                // Generate: unit -> base unit conversion
                if (unitDef.ToBaseUnit != null)
                {
                    var toBaseKey = $"{unitSymbol}|{baseUnit}";
                    autoConversions[toBaseKey] = UnitConversion.Function(
                        unitDef.ToBaseUnit,
                        $"Convert {unitSymbol} to base unit {baseUnit}"
                    );
                }
                
                // Generate: base unit -> unit conversion
                if (unitDef.FromBaseUnit != null)
                {
                    var fromBaseKey = $"{baseUnit}|{unitSymbol}";
                    autoConversions[fromBaseKey] = UnitConversion.Function(
                        unitDef.FromBaseUnit,
                        $"Convert base unit {baseUnit} to {unitSymbol}"
                    );
                }
            }
            
            return autoConversions;
        }
        
        /// <summary>
        /// Generates all possible conversions dynamically from UnitDefinition records
        /// NO MORE HARD-CODED MATRICES NEEDED!
        /// </summary>
        public Dictionary<string, UnitConversion> GetAllPossibleConversions()
        {
            var allConversions = new Dictionary<string, UnitConversion>();
            var unitsByFamily = GetUnitDefinitions().Values.GroupBy(u => u.Family);
            
            foreach (var familyGroup in unitsByFamily)
            {
                var unitsInFamily = familyGroup.Select(u => u.Symbol).ToList();
                var baseUnit = GetBaseUnits()[familyGroup.Key.ToString()];
                
                // Generate all unit-to-unit conversions within this family
                foreach (var fromUnit in unitsInFamily)
                {
                    foreach (var toUnit in unitsInFamily)
                    {
                        if (fromUnit != toUnit)
                        {
                            var conversionKey = $"{fromUnit}|{toUnit}";
                            allConversions[conversionKey] = UnitConversion.Function(
                                value => Convert(value, fromUnit, toUnit),
                                $"Convert {fromUnit} to {toUnit} via {baseUnit} base unit"
                            );
                        }
                    }
                }
            }
            
            return allConversions;
        }
        
        /// <summary>
        /// Validates that all base unit conversions are bidirectional and consistent
        /// </summary>
        public List<string> ValidateConversions(double tolerance = 1e-10)
        {
            var errors = new List<string>();
            var conversions = GetBaseUnitConversions();
            var baseUnits = GetBaseUnits();
            
            foreach (var family in baseUnits.Keys)
            {
                var baseUnit = baseUnits[family];
                var familyUnits = GetUnitDefinitions().Values
                    .Where(u => u.Family == family)
                    .Select(u => u.Symbol)
                    .Where(u => u != baseUnit)
                    .ToList();
                    
                foreach (var unit in familyUnits)
                {
                    var toBaseKey = $"{unit}|{baseUnit}";
                    var fromBaseKey = $"{baseUnit}|{unit}";
                    
                    // Check if both directions exist
                    if (!conversions.ContainsKey(toBaseKey))
                        errors.Add($"Missing conversion: {toBaseKey}");
                    if (!conversions.ContainsKey(fromBaseKey))
                        errors.Add($"Missing conversion: {fromBaseKey}");
                        
                    // Check if they're mathematically consistent (roundtrip test)
                    if (conversions.ContainsKey(toBaseKey) && conversions.ContainsKey(fromBaseKey))
                    {
                        var testValue = 1.0;
                        var roundTrip = conversions[fromBaseKey].Convert(conversions[toBaseKey].Convert(testValue));
                        if (Math.Abs(roundTrip - testValue) > tolerance)
                        {
                            errors.Add($"Roundtrip error for {unit}: {testValue} -> {roundTrip} (tolerance: {tolerance})");
                        }
                    }
                }
            }
            
            return errors;
        }
    }
}